server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/produto
    username: admin
    password: admin
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none